### ISSUE TITLE
UnboundLocalError: local variable 'final_adv' referenced before assignment

### ISSUE THREAD

**Issue by sakurachiyuki** [j40903272/MalConv-keras#8]
Hi.Thank you for the code.
When i run'python gen_adversarial.py ../saved/example.csv'

`FILE: /benign_samples/com.lekusoft.android.wallpaper.a20110701077.apk
	file length: 1215354 , Exceed max length ! Ignored !
	original score: 0.99955493
Traceback (most recent call last):
  File "gen_adversarial.py", line 115, in <module>
    adv_samples, log = gen_adv_samples(model, fn_list, args.pad_percent, args.step_size, args.thres)
  File "gen_adversarial.py", line 96, in gen_adv_samples
    bin_adv = bytes(list(final_adv))
UnboundLocalError: local variable 'final_adv' referenced before assignment
`
Is it the data problem?

**Comment by SmituSSupp** [comment]
> Hi.Thank you for the code.
> When i run'python gen_adversarial.py ../saved/example.csv'
> 
> `FILE: /benign_samples/com.lekusoft.android.wallpaper.a20110701077.apk file length: 1215354 , Exceed max length ! Ignored ! original score: 0.99955493 Traceback (most recent call last): File "gen_adversarial.py", line 115, in <module> adv_samples, log = gen_adv_samples(model, fn_list, args.pad_percent, args.step_size, args.thres) File "gen_adversarial.py", line 96, in gen_adv_samples bin_adv = bytes(list(final_adv)) UnboundLocalError: local variable 'final_adv' referenced before assignment `
> Is it the data problem?

Faced the same error. Did you find the solution by yourself or abandoned that idea?
